export const TypeItem = {
  ROLL_DOUBLE: "ROLL_DOUBLE",
  TURN_1_CELL: "TURN_1_CELL",
  X2_DIAMOND: "X2_DIAMOND",
  ROLL_TURN_BACK: "ROLL_TURN_BACK",
  ROLL_DOUBLE_SELECT_1: "ROLL_DOUBLE_SELECT_1",
};
