const Constants = {
  INCREASE_MONOPOLY_TICKETS: "INCREASE_MONOPOLY_TICKETS",
  DECREASE_MONOPOLY_TICKETS: "DECREASE_MONOPOLY_TICKETS",
  INCREASE_DIAMONDS: "INCREASE_DIAMONDS",
  DECREASE_DIAMONDS: "DECREASE_DIAMONDS",
  SET_DETAIL_PLATFORM: "SET_DETAIL_PLATFORM",
  SET_DETAIL_DIAMONDS: "SET_DETAIL_DIAMONDS",
  SET_DETAIL_TICKETS: "SET_DETAIL_TICKETS",
};

export default Constants;
