const Constants = {
  INCREASE_MONOPOLY_TICKETS: "INCREASE_MONOPOLY_TICKETS",
  DECREASE_MONOPOLY_TICKETS: "DECREASE_MONOPOLY_TICKETS",
  INCREASE_DIAMONDS: "INCREASE_DIAMONDS",
  DECREASE_DIAMONDS: "DECREASE_DIAMONDS",
};

export default Constants;
